# 配置框架(使用 java -jar app.jar --spring.profiles.active=develop | release | production 来启动项目, 其中 release 有时间就拿来测试, 而 production 存储在 Github 上, 每次修改 Github 配置就需要刷新(这个有时间可以优化为无需重启))
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:develop} # 默认启动开发环境
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/work_collaborative_images
    username: wci
    password: Qwe54188_

server:
  port: 5000

dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=Qwe54188_
    register-mode: instance
  protocol:
    name: tri
    port: 50050
  application:
    qos-enable: true
    name: user-server
    qos-port: 22222
    qos-accept-foreign-ip: false
    logger: slf4j
  provider:
    register: true
  metadata-report:
    parameters:
      cacheDir: ./cache

logging:
  level:
    cn.com.edtechhub.workuserserver: DEBUG